### ISSUE TITLE
Distribution/ release files

### ISSUE THREAD

**Issue by adbedada** [abeusher/timehash#14]
I w'd like to bring timehash to the Anaconda community under the conda-forge channel. 
Is there any plan to release a tarball file any time soon?

**Comment by abeusher** [comment]
Eddie,

Here you are:
https://github.com/abeusher/timehash/releases/tag/1.1 

Best,
Abe

**Comment by adbeda** [comment]
Abe, 
This is awesome!

Thanks,
Eddie

**Comment by adbedada** [comment]
Abe, good news!
timehash is now available on conda-forge

  ##### Installation

      conda install -c conda-forge timehash

Thanks!
-Eddie
